AzureKeyVault.LetsEncrypt/AddCertificate.cs
AzureKeyVault.LetsEncrypt/AzureKeyVault.LetsEncrypt.csproj
AzureKeyVault.LetsEncrypt/SharedFunctions.cs
README.md

Adding DNS lookup validation

---

AzureKeyVault.LetsEncrypt/SharedFunctions.cs

Fixed DNS validation error in SAN certificate

---

KeyVault.Acmebot/RenewCertificatesFunctions.cs

Fixed certificate renewal to continue even if it failed

---

KeyVault.Acmebot/Contracts/ISharedFunctions.cs
KeyVault.Acmebot/GetDnsZonesFunctions.cs
KeyVault.Acmebot/Providers/AzureDnsProvider.cs
KeyVault.Acmebot/Providers/DnsZone.cs
KeyVault.Acmebot/Providers/IDnsProvider.cs
KeyVault.Acmebot/SharedFunctions.cs
KeyVault.Acmebot/Startup.cs

Working for #76 
- Added `IDnsProvider` interface
- Implemented `AzureDnsProvider` class

Adding DNS provider model

---

KeyVault.Acmebot/AddCertificateFunctions.cs
KeyVault.Acmebot/index.html

Adding client-side error handling

---

KeyVault.Acmebot/AcmebotOptions.cs
KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs
KeyVault.Acmebot/Internal/WebhookLifeCycleNotification.cs
KeyVault.Acmebot/Internal/X509Certificate2Extensions.cs
KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/SharedFunctions.cs
KeyVault.Acmebot/Startup.cs
README.md
README_ja.md
azuredeploy.json

Support for ACME certification authorities other than Let's Encrypt

---

azuredeploy.json

Fixed Azure Resouce naming rule

---

README.md

Added description of more of the created configuration.
Added instructions for delete of a certificate and update/reinstall of function app

Update to readme with more configuration, update and delete instructions

---

KeyVault.Acmebot/Contracts/ISharedFunctions.cs
KeyVault.Acmebot/GetCertificatesFunctions.cs
KeyVault.Acmebot/Providers/AzureDnsProvider.cs
KeyVault.Acmebot/Providers/CloudflareProvider.cs
KeyVault.Acmebot/Providers/GratisDnsProvider.cs
KeyVault.Acmebot/Providers/IDnsProvider.cs
KeyVault.Acmebot/SharedFunctions.cs

Changed to delete created DNS records after completion

---

KeyVault.Acmebot/Internal/CertificateExtensions.cs

Fixed missing SANs certificate error

---

KeyVault.Acmebot/Contracts/ISharedFunctions.cs
KeyVault.Acmebot/SharedFunctions.cs
KeyVault.Acmebot/host.json

Improvement ACME challenge error log

---

KeyVault.Acmebot/Providers/AzureDnsProvider.cs
KeyVault.Acmebot/Providers/CloudflareProvider.cs
KeyVault.Acmebot/Providers/GratisDnsProvider.cs
KeyVault.Acmebot/Providers/IDnsProvider.cs
KeyVault.Acmebot/SharedFunctions.cs
KeyVault.Acmebot/Startup.cs

Fixed the DNS record validation to be stable

---

KeyVault.Acmebot/SharedFunctions.cs

Fixed getting DNS zone error handling

---

azuredeploy.json

Changed the base URL of the Key Vault to be entered during deployment

---

KeyVault.Acmebot/Providers/GoogleDnsProvider.cs

https://github.com/shibayan/keyvault-acmebot/issues/184

Removed dot from substring

---

README.md

Update document for Azure DNS delete-lock

---

.github/workflows/publish.yml

Publish package for win-x86 runtime only

---

KeyVault.Acmebot/static/add-certificate.html

Adding multi-domain certificate support

---

KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Options/DnsMadeEasyOptions.cs
KeyVault.Acmebot/Providers/DnsMadeEasyProvider.cs
KeyVault.Acmebot/Startup.cs
README.md
README_ja.md

Our company uses the DNS Made Easy as a provider for DNS.

Implements DNS Made Easy provider

---

azuredeploy.json

Adding ARM Template outputs

---

KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Functions/StaticPage.cs
KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/proxies.json
KeyVault.Acmebot/static/bulk-certificate.html

Adding advanced mode to Web UI

---

KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Providers/AzureDnsProvider.cs
KeyVault.Acmebot/Providers/CloudflareProvider.cs
KeyVault.Acmebot/Providers/DnsZone.cs
KeyVault.Acmebot/Providers/GoogleDnsProvider.cs

Adding enhanced name servers validation

---

KeyVault.Acmebot/Startup.cs

Fixed AzureDns configuration order

---

KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs
KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Options/ExternalAccountBindingOptions.cs

This reverts commit c85afd26085a14738dd6091e4dbedb426440a8fd.

Revert "Adding External Account Binding support"

---

.editorconfig
.github/workflows/build.yml
.github/workflows/publish.yml
.gitmodules
KeyVault.Acmebot.sln
KeyVault.Acmebot/Functions/RenewCertificates.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/RetriableOrchestratorException.cs

Added retries for temporary errors when renewing certificates

---

KeyVault.Acmebot/Functions/ISharedActivity.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Functions/SharedOrchestrator.cs
KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs
KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Options/ExternalAccountBindingOptions.cs
README.md
azuredeploy.json

Adding External Account Binding support

---

KeyVault.Acmebot/Internal/AcmeProtocolClientExtensions.cs

Changed to search for alternate first when PreferredChain is specified

---

azuredeploy.json

RBAC for Key Vault data-plane authz GA
https://azure.microsoft.com/en-us/updates/azure-rolebased-access-control-rbac-for-azure-key-vault-data-plane-authorization-is-now-available/
Close #213

Adding Key Vault RBAC Authorization option

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Options/Route53Options.cs
KeyVault.Acmebot/Providers/Route53Provider.cs
KeyVault.Acmebot/Startup.cs
README.md

Adding Amazon Route 53 provider

---

KeyVault.Acmebot/Providers/Route53Provider.cs

Fixed an unintended records were deleted in Route 53 provider

---

KeyVault.Acmebot/Functions/RenewCertificates.cs

Change renew retry interval

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Options/GoDaddyOptions.cs
KeyVault.Acmebot/Providers/GoDaddyProvider.cs
KeyVault.Acmebot/Startup.cs

Submitting an implementation of a provider for GoDaddy.

Adding GoDaddy Provider

---

KeyVault.Acmebot/Functions/ISharedActivity.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Functions/SharedOrchestrator.cs

If a Key Vault certificate policy already exists, reuse it.

Reuse existing certificate policy

---

KeyVault.Acmebot/Functions/AddCertificate.cs
KeyVault.Acmebot/Functions/RenewCertificates.cs
KeyVault.Acmebot/Functions/SharedOrchestrator.cs
KeyVault.Acmebot/Models/AddCertificateRequest.cs
KeyVault.Acmebot/static/add-certificate.html
KeyVault.Acmebot/static/bulk-certificate.html
KeyVault.Acmebot/static/renew-certificate.html

Changed the name of Key Vault certificates to be customizable

---

README.md

Update App Service Authentication section

---

KeyVault.Acmebot/Models/CertificatePolicyItem.cs
KeyVault.Acmebot/static/bulk-certificate.html

Fixed `KeyType` null error

---

KeyVault.Acmebot/Internal/WebhookInvoker.cs

Add logging for Webhook invoke failure

---

KeyVault.Acmebot/Functions/RenewCertificates.cs

Adding ACME request level retries

---

KeyVault.Acmebot/Functions/RenewCertificates.cs

Adding jitter for renew certificates

---

KeyVault.Acmebot/Functions/ISharedActivity.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Functions/SharedOrchestrator.cs
KeyVault.Acmebot/static/add-certificate.html
KeyVault.Acmebot/static/renew-certificate.html

Fixed Buypass Go SSL issuing error

---

KeyVault.Acmebot/Internal/WebhookInvoker.cs

Fixed teams webhook issue and improvement format

---

KeyVault.Acmebot/static/add-certificate.html
KeyVault.Acmebot/static/bulk-certificate.html
KeyVault.Acmebot/static/renew-certificate.html

Update Vue.js and libraries

---

KeyVault.Acmebot/Providers/GoDaddyProvider.cs

Improvement GoDaddy provider

---

KeyVault.Acmebot/Providers/CloudflareProvider.cs
KeyVault.Acmebot/Providers/DnsZone.cs
KeyVault.Acmebot/Providers/GoDaddyProvider.cs

Always apply punycode conversion

---

KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Internal/X509Certificate2Extensions.cs

Fixed incorrect order of certificate chains

---

.editorconfig
.github/workflows/build.yml
azuredeploy.bicep
azuredeploy.json

Close #420 
In the future, the Container Registry will release an official bicep module.

Adding bicep template

---

KeyVault.Acmebot/Internal/CertificateExtensions.cs
KeyVault.Acmebot/Models/CertificateItem.cs
KeyVault.Acmebot/wwwroot/dashboard/index.html
azuredeploy.json

Fixed to prevent revocation of expired certificates

---

KeyVault.Acmebot/Functions/RenewCertificates.cs

Thanks https://opensource.microsoft.com/azure-credits/

Changed the execution timing of update triggers to daily

---

KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Options/AcmebotOptions.cs

`Acmebot:RenewBeforeExpiry` option name

Adding `RenewBeforeExpiry` option

---

azuredeploy.json

Update to latest ACMESharpCore

---

KeyVault.Acmebot/Functions/RenewCertificates.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Internal/ApplicationVersionInitializer.cs
KeyVault.Acmebot/Internal/AzureEnvironment.cs
KeyVault.Acmebot/Internal/CertificateExtensions.cs
KeyVault.Acmebot/Internal/DnsProvidersExtensions.cs
KeyVault.Acmebot/Providers/AzureDnsProvider.cs
KeyVault.Acmebot/Providers/CloudflareProvider.cs
KeyVault.Acmebot/Providers/DnsMadeEasyProvider.cs
KeyVault.Acmebot/Providers/DnsZone.cs
KeyVault.Acmebot/Providers/GandiProvider.cs
KeyVault.Acmebot/Providers/GoDaddyProvider.cs
KeyVault.Acmebot/Providers/GoogleDnsProvider.cs
KeyVault.Acmebot/Providers/Route53Provider.cs
KeyVault.Acmebot/Providers/TransIpProvider.cs
KeyVault.Acmebot/Startup.cs
KeyVault.Acmebot/host.json

Adding multiple DNS providers support

---

.editorconfig
.github/workflows/build.yml
.github/workflows/publish.yml
azuredeploy.bicep
azuredeploy.json

Improvement bicep module

---

KeyVault.Acmebot/Functions/SharedActivity.cs

Fixed ACME order status validation

---

KeyVault.Acmebot/Providers/CloudflareProvider.cs

Fixes https://github.com/shibayan/keyvault-acmebot/discussions/485#discussioncomment-3204983

Fixed NS validation using Cloudflare custom name server

---

KeyVault.Acmebot/Internal/AcmeProtocolClientExtensions.cs

Fixed crash when Link header does not exist

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj

Update NuGet packages

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj

Update Azure.Identity and nuget packages

---

KeyVault.Acmebot/wwwroot/dashboard/index.html

Added display of confirmation popup before revoke

---

KeyVault.Acmebot/Internal/AccountKey.cs
KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs
README.md

Adding to `Acmebot:DefaultSigner` option

---

KeyVault.Acmebot/Functions/GetDnsZones.cs
KeyVault.Acmebot/Functions/ISharedActivity.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Functions/SharedOrchestrator.cs
KeyVault.Acmebot/Internal/CertificateExtensions.cs
KeyVault.Acmebot/Internal/CertificatePolicyExtensions.cs
KeyVault.Acmebot/Internal/DnsProvidersExtensions.cs
KeyVault.Acmebot/Internal/DnsZoneExtensions.cs
KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/Models/CertificateItem.cs
KeyVault.Acmebot/Models/CertificatePolicyItem.cs
KeyVault.Acmebot/Models/DnsZoneItem.cs
KeyVault.Acmebot/wwwroot/dashboard/index.html

Modified to retain DNS Provider name when certificates are issued

---

KeyVault.Acmebot/Functions/GetDnsZones.cs
KeyVault.Acmebot/Functions/ISharedActivity.cs
KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Internal/DnsProvidersExtensions.cs
KeyVault.Acmebot/Internal/DnsZoneExtensions.cs
KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/Models/DnsZoneItem.cs
KeyVault.Acmebot/wwwroot/dashboard/index.html

This pull request displays DNS zones in an easy-to-understand format for each configured DNS provider.
Close #734

Improvement dns zones dropdown list

---

KeyVault.Acmebot/Providers/GoogleDnsProvider.cs

This fixes a bug that prevented all items from being retrieved when there were a large number of zones.

Google DNS: Fixed a problem where not all zones could be retrieved

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj
KeyVault.Acmebot/Providers/Route53Provider.cs

This fixes a bug that prevented all items from being retrieved when there were a large number of zones.
Close #707

Route 53: Fixed a problem where not all zones could be retrieved

---

KeyVault.Acmebot/KeyVault.Acmebot.csproj

Added preserved dependency System.Memory.Data

---

KeyVault.Acmebot/Functions/SharedActivity.cs
KeyVault.Acmebot/Internal/CertificateExtensions.cs

Fixed new certificate issue error

---

KeyVault.Acmebot/Internal/Constants.cs
KeyVault.Acmebot/Internal/GenericPayloadBuilder.cs
KeyVault.Acmebot/Startup.cs

Adding generic webhook to extra detail.
- `functionAppName` : Running Azure Function name
- `keyVaultName` : Key Vault host name
Close #686

Adding generic webhook extra data

---

KeyVault.Acmebot/Internal/AcmeProtocolClientFactory.cs

Fixed an error caused by the discontinuation of Let's Encrypt's Contact

---

KeyVault.Acmebot/Options/AcmebotOptions.cs
KeyVault.Acmebot/Startup.cs

Support to User-Assigned managed identity
